name: prometheus-speedtest
base: core20
version: git
summary: A Prometheus exporter for measuring Internet connection bandwidth
description: |
    prometheus-speedtest uses the speedtest.net network of bandwidth measurement
    servers to measure download and upload bandwidth of an Internet connection
    at a specific point in time, providing this information to Prometheus.

grade: stable
confinement: strict

apps:
  daemon:
    plugs:
      - network
      - network-bind
    command: bin/prometheus_speedtest
    daemon: simple
parts:
  prometheus-speedtest:
    plugin: python
    stage-packages:
        - python3-venv
    source: .
