name: test
on:
  push:
  workflow_dispatch:
  pull_request:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@v6
        with:
            python-version: 3.14
            cache: pip
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 4.0.2
          bundler-cache: true
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt -r requirements-dev.txt
          gem install mdl
      - uses: pre-commit/action@v3.0.1
      - name: pytest
        run: pytest
