name: test
on:
  push:
  workflow_dispatch:
  pull_request:
  schedule:
    - cron: '0 0 1 * *'  # On the first of every month
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
            python-version: 3.12
            cache: pip
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3
          bundler-cache: true
      - name: Install Dependencies
        run: |
          pip install -r requirements.txt -r requirements-dev.txt
          gem install mdl
      - uses: pre-commit/action@v3.0.1
      - name: pytest
        run: pytest
